### ISSUE TITLE
CI deploy to pypi is not  working properly

### ISSUE THREAD

**Issue by andre-filho** [andre-filho/commit-helper#68]
**Describe the bug**
bdist packages in step before deploy are not being packaged properly

**Expected behavior**
bdist create a correct package and submit it to pypi

**Screenshots**
![image](https://user-images.githubusercontent.com/15203968/49803306-94203480-fd36-11e8-844a-0afd4934caae.png)
full job report for travis ci: [click here](https://travis-ci.org/andre-filho/commit-helper/jobs/466503992)

**Comment by alaxalves** [comment]
Hey @andre-filho I'm interested on working with this. Could you explain a little more about this issue?

**Comment by andre-filho** [comment]
@alaxalves to upload a something to pypi, you are supposed to generate the dists. Currently this is being done in the before_deploy step in the travis.yml as `python3 setup.py sdist bdist_wheel`.

This step and the deploy steps succeed but uploads an empty package to the pypi repo, whereas it should send the dists generated by the before_step.

The error above shows that the .egg package is not being generated properly (missing files) when installing a release generated through the CD workflow.

Maybe the problem is travis inner workings, if somehow it deletes generated files between steps.

**Comment by andre-filho** [comment]
@alaxalves I've solved this definitely by changing the provider from pypi to script. Seems like travis' pypi  provider wasn't that great at all. Lesson learned.

**Comment by alaxalves** [comment]
@andre-filho I fell like I had already experienced this, it been looking out through my previous projects and I found out that Travis really is the problem, because apparently you can't persist "artifacts" along every travis job. What solved my issue at the time was adding this in my `.travis.yml`:
``` yaml
    edge:
      branch: v1.8.45
```
And my entire deploy stage looked something like this:
``` yaml
deploy:
  - provider: pypi
    user: alaxalves
    password:
      secure: blablablabla
    on:
      branch: master
      python: 3.5
    edge:
      branch: v1.8.45
```
